USE marketplace_analytics;

CREATE TABLE IF NOT EXISTS staging_vehicle_ndjson (
  staging_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  json_text LONGTEXT NOT NULL,
  json_doc JSON GENERATED ALWAYS AS (CAST(json_text AS JSON)) STORED,
  loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (staging_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS staging_part_ndjson (
  staging_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  json_text LONGTEXT NOT NULL,
  json_doc JSON GENERATED ALWAYS AS (CAST(json_text AS JSON)) STORED,
  loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (staging_id)
) ENGINE=InnoDB;
